name: movieverse
description: "A movie and TV show browsing app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # State Management
  provider: ^6.1.1

  # Network
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1

  # Caching
  shared_preferences: ^2.2.0
  cached_network_image: ^3.3.1

  # Dependency Injection
  get_it: ^7.6.7

  # Utils
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  intl: ^0.19.0

  # Video Player
  youtube_player_iframe: ^5.0.0
  card_swiper: ^3.0.1
  url_launcher: ^6.2.5

  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.17.5
  firebase_analytics: ^10.10.7
  firebase_database: ^10.5.7
  firebase_messaging: ^14.7.10
  firebase_crashlytics: ^3.5.7
  firebase_performance: ^0.9.4+7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
