// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcgKNikdR3XyHBi8c8CedyP1MGZntxGoM',
    appId: '1:300238429893:web:2973b611f5e3c259975aac',
    messagingSenderId: '300238429893',
    projectId: 'movieverse-bd77e',
    authDomain: 'movieverse-bd77e.firebaseapp.com',
    databaseURL: 'https://movieverse-bd77e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'movieverse-bd77e.firebasestorage.app',
    measurementId: 'G-8EK52BVMCV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdMzpQ7zY73T35i2Yy1wraDkWF0utSYwU',
    appId: '1:300238429893:android:1de98a3eba7e969a975aac',
    messagingSenderId: '300238429893',
    projectId: 'movieverse-bd77e',
    databaseURL: 'https://movieverse-bd77e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'movieverse-bd77e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvHpoUR738kUO0M3PJjAzzxKpxygsnsYQ',
    appId: '1:300238429893:ios:4c3861e0eabe7982975aac',
    messagingSenderId: '300238429893',
    projectId: 'movieverse-bd77e',
    databaseURL: 'https://movieverse-bd77e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'movieverse-bd77e.firebasestorage.app',
    iosBundleId: 'com.example.newMovieverse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvHpoUR738kUO0M3PJjAzzxKpxygsnsYQ',
    appId: '1:300238429893:ios:4c3861e0eabe7982975aac',
    messagingSenderId: '300238429893',
    projectId: 'movieverse-bd77e',
    databaseURL: 'https://movieverse-bd77e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'movieverse-bd77e.firebasestorage.app',
    iosBundleId: 'com.example.newMovieverse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcgKNikdR3XyHBi8c8CedyP1MGZntxGoM',
    appId: '1:300238429893:web:7e214b29ec83a298975aac',
    messagingSenderId: '300238429893',
    projectId: 'movieverse-bd77e',
    authDomain: 'movieverse-bd77e.firebaseapp.com',
    databaseURL: 'https://movieverse-bd77e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'movieverse-bd77e.firebasestorage.app',
    measurementId: 'G-K67BCXD6J7',
  );

}